{% set version = "4.5.1" %}

package:
  name: libctl
  version: {{ version }}

source:
  url: https://github.com/NanoComp/libctl/releases/download/v{{ version }}/libctl-{{ version }}.tar.gz
  sha256: fcfeb2f13dda05b560f0ec6872757d9318fdfe8f4bc587eb2053a29ba328ae25

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libctlgeom${SHLIB_EXT}

about:
  home: https://github.com/NanoComp/libctl
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: A Guile-based library for supporting flexible control files in scientific simulations
  doc_url: https://libctl.readthedocs.io
  dev_url: https://github.com/NanoComp/libctl

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
    - RobinD42
