{% set name = "libctl" %}
{% set version = "4.5.0" %}
{% set sha256 = "621e46a238c4d5e8ce0866183f8e04abac6e1a94d90932af0d56ee61370ea153" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/NanoComp/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libctlgeom${SHLIB_EXT}

about:
  home: https://github.com/NanoComp/libctl
  license: GPL-2.0-or-later
  license_file: COPYING
  summary:  A Guile-based library for supporting flexible control files in scientific simulations
  doc_url: https://libctl.readthedocs.io
  dev_url: https://github.com/NanoComp/libctl

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
    - RobinD42
