{% set name = "libctl" %}
{% set version = "4.2.0" %}
{% set sha256 = "0341ad6ea260ecda2efb3d4b679abb3d05ca6211792381979b036177a9291975" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/stevengj/{{ name }}/releases/download/v{{version}}/{{ name }}-{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libctlgeom.so     # [linux]
    - test -f ${PREFIX}/lib/libctlgeom.dylib  # [osx]

about:
  home: http:/github.com/stevengj/libctl
  license: GPL-2.0
  license_file: COPYING
  summary:  A Guile-based library for supporting flexible control files in scientific simulations
  doc_url: http://libctl.readthedocs.io
  dev_url: https://github.com/stevengj/libctl

extra:
  recipe-maintainers:
    - ChristopherHogan
