{% set version = "4.6.0" %}

package:
  name: libctl
  version: {{ version }}

source:
  url: https://github.com/NanoComp/libctl/releases/download/v{{ version }}/libctl-{{ version }}.tar.gz
  sha256: 07463194568868d0b207ad85dc89e367435505f4200020011d3c37739971112a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/libctlgeom${SHLIB_EXT}

about:
  home: https://github.com/NanoComp/libctl
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: A Guile-based library for supporting flexible control files in scientific simulations
  doc_url: https://libctl.readthedocs.io
  dev_url: https://github.com/NanoComp/libctl

extra:
  recipe-maintainers:
    - ChristopherHogan
    - oskooi
    - RobinD42
